CREATE DATABASE UnicaContabil /*!40100 COLLATE 'utf8mb4_general_ci' */;


CREATE TABLE HistReceitasBrutas (
	CNPJ VARCHAR(18) NULL DEFAULT NULL,
	DT_COMPETENCIA DATE NULL DEFAULT NULL,
	VL_MI DOUBLE NULL DEFAULT NULL,
	VL_ME DOUBLE NULL DEFAULT NULL
)
COLLATE='utf8mb4_general_ci';
